services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SPRING_PROFILES_ACTIVE=release
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/spoc
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=spoc-server-123456
    networks:
      - mynetwork
    depends_on:
      - db
#      - redis

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: spoc-server-123456
      MYSQL_DATABASE: spoc
    ports:
      - "3306:3306"
    networks:
      - mynetwork
#  redis:
#    image: redis:6.2.14
#    ports:
#      - "6379:6379"
#    networks:
#      - mynetwork
networks:
  mynetwork:
    driver: bridge
