services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SPRING_PROFILES_ACTIVE=release
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/spoc
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=spoc-server-123456
    networks:
      - user-service-network
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: spoc-server-123456
      MYSQL_DATABASE: spoc
    ports:
      - "3306:3306"
    networks:
      - user-service-network
networks:
  user-service-network:
    external: true
