name: Java CI with Maven for Microservices

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # 打包第一个微服务
    - name: Build and Package Service 1
      run: mvn -B package --file api-gateway/pom.xml -DskipTests

    - name: Upload Service 1 Artifact
      uses: actions/upload-artifact@v3
      with:
        name: service-1-artifact
        path: api-gateway/target/*.jar

    # 打包第二个微服务
    - name: Build and Package Service 2
      run: mvn -B package --file course-service/pom.xml -DskipTests

    - name: Upload Service 2 Artifact
      uses: actions/upload-artifact@v3
      with:
        name: service-2-artifact
        path: course-service/target/*.jar

    # 打包第三个微服务
    - name: Build and Package Service 3
      run: mvn -B package --file user-course-service/pom.xml -DskipTests

    - name: Upload Service 3 Artifact
      uses: actions/upload-artifact@v3
      with:
        name: service-3-artifact
        path: service-3/target/*.jar
